#!/usr/bin/env sh
#SSL Keys ändern
cd /etc/ssh/
mkdir default_kali_keys
mv ssh_host_* default_kali_keys/
dpkg-reconfigure openssh-server
md5sum ssh_host_*
cd default_kali_keys/
md5sum *


#VM Ware
apt-get -y install -y virtualbox-guest-x11

#MSF Setup
systemctl start postgresql
systemctl enable postgresql

msfconsole -x "msfdb init;msfdb start;exit -y"


#https://github.com/rebootuser/LinEnum/blob/master/LinEnum.sh

#terminator
apt-get -y install terminator

#tldr kürzere manpages
apt-get -y install tldr

#mtr Kombination aus traceroute und ping
apt-get -y install mtr

#screenfetch für Systeminfos
apt-get -y install screenfetch 
 
#cherrytreefürnotizen
apt-get -y install cherrytree

#arachni
apt-get -y install build-essential curl libcurl3 libcurl4-openssl-dev ruby ruby-dev
apt-get -y install arachni

#nmap input für searchsploit aktivieren
apt -y install libxml2-utils


#Kali Bleeding edge

echo deb http://http.kali.org/kali kali-bleeding-edge contrib non-free main >> /etc/apt/sources.list
apt-get -y update
apt-get -y upgrade

#Burp support

apt-get -y install openjdk-6-jdk
#exploits compilieren
apt-get -y install gcc-multilib
apt-get -y install  lib32z1 lib32ncurses5
 #(um 32 bit zu compilen)
install -y libc6:i386 libncurses5:i386 libstdc++6:i386

#veil
apt-get -y install veil-evasion
veil --setup

#pentesthelferscripte etc herunterladen
mkdir pentesttools
mkdir pentesttools/payloadhandler
cd pentesttools/payloadhandler
wget https://raw.githubusercontent.com/ucki/multipass/master/multipass.sh
chmod 77 multipass.sh 
cd ..
mkdir enumscripts
cd enumscripts
wget https://raw.githubusercontent.com/Arr0way/linux-local-enumeration-script/master/linux-local-enum.sh



